-- =============================================================================
-- 20260602030000_add_receivable_billing_schema.sql
--
-- 売掛管理・月次請求書発行機能 (receivable-billing) のスキーマを追加する。
--
-- 仕様:
--   .kiro/specs/receivable-billing/design.md (Data Model)
--
-- 追加テーブル:
--   1. company_profile          (自社情報、シングルトン)
--   2. companies                 (取引先マスタ)
--   3. invoices                  (請求書ヘッダ)
--   4. accounts_receivable       (売掛明細、invoices に FK)
--   5. daily_sales               (日次売上集計)
--   6. daily_staff_sales         (スタッフ別日次売上)
--   7. staff_rates               (スタッフ単価マスタ)
--   8. monthly_fixed_expenses    (月額固定経費)
--
-- 初期データ (company_profile / companies / staff_rates) は別マイグレーション
--   20260602030500_seed_receivable_billing.sql
-- に分離する。
--
-- RLS: 全テーブルで有効化、authenticated ロールのみ full access。
--      anon ロールは一切アクセス不可 (機密データのため)。
--
-- update_updated_at_column() トリガー関数は initial_schema.sql で既に定義済み。
-- =============================================================================

-- ===== 1. company_profile (自社情報、シングルトン) =====
CREATE TABLE IF NOT EXISTS public.company_profile (
  id                   SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  name                 TEXT NOT NULL,
  postal_code          TEXT NOT NULL,
  address              TEXT NOT NULL,
  invoice_number       TEXT NOT NULL,
  bank                 TEXT NOT NULL,
  bank_branch          TEXT NOT NULL,
  bank_account_type    TEXT NOT NULL,
  bank_account_number  TEXT NOT NULL,
  bank_account_holder  TEXT NOT NULL,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ===== 2. companies (取引先マスタ) =====
CREATE TABLE IF NOT EXISTS public.companies (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                 TEXT NOT NULL UNIQUE,
  invoice_display_name TEXT,
  aliases              TEXT[] NOT NULL DEFAULT '{}',
  display_order        INTEGER NOT NULL DEFAULT 0,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  memo                 TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_companies_active_order
  ON public.companies (is_active, display_order);

CREATE INDEX IF NOT EXISTS idx_companies_aliases_gin
  ON public.companies USING GIN (aliases);

-- ===== 3. invoices (請求書ヘッダ) =====
-- accounts_receivable が invoice_id を参照するため、先に作成する。
CREATE TABLE IF NOT EXISTS public.invoices (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id        BIGINT NOT NULL REFERENCES public.companies (id) ON DELETE RESTRICT,
  billing_month     DATE NOT NULL CHECK (EXTRACT(DAY FROM billing_month) = 1),
  issue_date        DATE NOT NULL,
  total_amount      INTEGER NOT NULL CHECK (total_amount >= 0),
  line_count        INTEGER NOT NULL CHECK (line_count >= 0),
  file_path         TEXT,
  paid_at           TIMESTAMPTZ,
  profile_snapshot  JSONB NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company_id, billing_month)
);

CREATE INDEX IF NOT EXISTS idx_invoices_billing_month
  ON public.invoices (billing_month);

CREATE INDEX IF NOT EXISTS idx_invoices_unpaid
  ON public.invoices (paid_at)
  WHERE paid_at IS NULL;

-- ===== 4. accounts_receivable (売掛明細) =====
CREATE TABLE IF NOT EXISTS public.accounts_receivable (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id     BIGINT NOT NULL REFERENCES public.companies (id) ON DELETE RESTRICT,
  billing_month  DATE NOT NULL CHECK (EXTRACT(DAY FROM billing_month) = 1),
  work_date      DATE NOT NULL,
  departure      TEXT,
  destination    TEXT,
  amount         INTEGER NOT NULL CHECK (amount >= 0),
  note           TEXT,
  invoice_id     BIGINT REFERENCES public.invoices (id) ON DELETE SET NULL,
  source_file    TEXT,
  imported_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE NULLS NOT DISTINCT
    (billing_month, company_id, work_date, departure, destination, amount)
);

CREATE INDEX IF NOT EXISTS idx_ar_billing_month_company
  ON public.accounts_receivable (billing_month, company_id);

CREATE INDEX IF NOT EXISTS idx_ar_invoice_id
  ON public.accounts_receivable (invoice_id);

CREATE INDEX IF NOT EXISTS idx_ar_unbilled
  ON public.accounts_receivable (billing_month, company_id)
  WHERE invoice_id IS NULL;

-- ===== 5. daily_sales (日次売上集計) =====
-- total_sales / profit は GENERATED 列。
CREATE TABLE IF NOT EXISTS public.daily_sales (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_date             DATE NOT NULL UNIQUE,
  vehicle1_distance_km  NUMERIC(8,2),
  vehicle2_distance_km  NUMERIC(8,2),
  vehicle1_fuel_yen     INTEGER,
  vehicle2_fuel_yen     INTEGER,
  vehicle1_sales        INTEGER NOT NULL DEFAULT 0 CHECK (vehicle1_sales >= 0),
  vehicle2_sales        INTEGER NOT NULL DEFAULT 0 CHECK (vehicle2_sales >= 0),
  vehicle3_sales        INTEGER NOT NULL DEFAULT 0 CHECK (vehicle3_sales >= 0),
  total_sales           INTEGER GENERATED ALWAYS AS
                          (vehicle1_sales + vehicle2_sales + vehicle3_sales) STORED,
  total_hours           NUMERIC(6,2) NOT NULL DEFAULT 0,
  receivable_total      INTEGER NOT NULL DEFAULT 0,
  expense_note          TEXT,
  expense_amount        INTEGER NOT NULL DEFAULT 0 CHECK (expense_amount >= 0),
  cash                  INTEGER NOT NULL DEFAULT 0,
  profit                INTEGER GENERATED ALWAYS AS (
                            (vehicle1_sales + vehicle2_sales + vehicle3_sales)
                            - expense_amount
                            - COALESCE(vehicle1_fuel_yen, 0)
                            - COALESCE(vehicle2_fuel_yen, 0)
                          ) STORED,
  source_file           TEXT,
  imported_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_sales_year_month
  ON public.daily_sales (date_trunc('month', work_date));

-- ===== 6. daily_staff_sales (スタッフ別日次売上) =====
CREATE TABLE IF NOT EXISTS public.daily_staff_sales (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_date    DATE NOT NULL,
  staff_name   TEXT NOT NULL,
  sales        INTEGER NOT NULL DEFAULT 0 CHECK (sales >= 0),
  hours        NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (hours >= 0),
  source_file  TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (work_date, staff_name)
);

CREATE INDEX IF NOT EXISTS idx_daily_staff_sales_work_date
  ON public.daily_staff_sales (work_date);

-- ===== 7. staff_rates (スタッフ単価マスタ) =====
CREATE TABLE IF NOT EXISTS public.staff_rates (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_name      TEXT NOT NULL UNIQUE,
  rate_type       TEXT NOT NULL CHECK (rate_type IN ('hourly', 'commission')),
  hourly_rate     INTEGER CHECK (hourly_rate IS NULL OR hourly_rate >= 0),
  commission_rate NUMERIC(4,3) CHECK (commission_rate IS NULL OR commission_rate >= 0),
  display_order   INTEGER NOT NULL DEFAULT 0,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  memo            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (
    (rate_type = 'hourly'     AND hourly_rate     IS NOT NULL AND commission_rate IS NULL) OR
    (rate_type = 'commission' AND commission_rate IS NOT NULL AND hourly_rate     IS NULL)
  )
);

-- ===== 8. monthly_fixed_expenses (月額固定経費) =====
CREATE TABLE IF NOT EXISTS public.monthly_fixed_expenses (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  billing_month  DATE NOT NULL CHECK (EXTRACT(DAY FROM billing_month) = 1),
  label          TEXT NOT NULL,
  amount         INTEGER NOT NULL DEFAULT 0 CHECK (amount >= 0),
  source_file    TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (billing_month, label)
);

CREATE INDEX IF NOT EXISTS idx_monthly_fixed_expenses_billing_month
  ON public.monthly_fixed_expenses (billing_month);

-- ===== updated_at トリガー =====
DROP TRIGGER IF EXISTS update_company_profile_updated_at ON public.company_profile;
CREATE TRIGGER update_company_profile_updated_at
  BEFORE UPDATE ON public.company_profile
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_companies_updated_at ON public.companies;
CREATE TRIGGER update_companies_updated_at
  BEFORE UPDATE ON public.companies
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_invoices_updated_at ON public.invoices;
CREATE TRIGGER update_invoices_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_accounts_receivable_updated_at ON public.accounts_receivable;
CREATE TRIGGER update_accounts_receivable_updated_at
  BEFORE UPDATE ON public.accounts_receivable
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_daily_sales_updated_at ON public.daily_sales;
CREATE TRIGGER update_daily_sales_updated_at
  BEFORE UPDATE ON public.daily_sales
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_daily_staff_sales_updated_at ON public.daily_staff_sales;
CREATE TRIGGER update_daily_staff_sales_updated_at
  BEFORE UPDATE ON public.daily_staff_sales
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_staff_rates_updated_at ON public.staff_rates;
CREATE TRIGGER update_staff_rates_updated_at
  BEFORE UPDATE ON public.staff_rates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_monthly_fixed_expenses_updated_at ON public.monthly_fixed_expenses;
CREATE TRIGGER update_monthly_fixed_expenses_updated_at
  BEFORE UPDATE ON public.monthly_fixed_expenses
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===== RLS 有効化 (全テーブル authenticated only) =====
-- 売上・売掛は機密情報のため anon は一切アクセス不可。
ALTER TABLE public.company_profile        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accounts_receivable    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_sales            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_staff_sales      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_rates            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_fixed_expenses ENABLE ROW LEVEL SECURITY;

-- company_profile
DROP POLICY IF EXISTS "authenticated_full" ON public.company_profile;
CREATE POLICY "authenticated_full" ON public.company_profile
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- companies
DROP POLICY IF EXISTS "authenticated_full" ON public.companies;
CREATE POLICY "authenticated_full" ON public.companies
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- invoices
DROP POLICY IF EXISTS "authenticated_full" ON public.invoices;
CREATE POLICY "authenticated_full" ON public.invoices
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- accounts_receivable
DROP POLICY IF EXISTS "authenticated_full" ON public.accounts_receivable;
CREATE POLICY "authenticated_full" ON public.accounts_receivable
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- daily_sales
DROP POLICY IF EXISTS "authenticated_full" ON public.daily_sales;
CREATE POLICY "authenticated_full" ON public.daily_sales
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- daily_staff_sales
DROP POLICY IF EXISTS "authenticated_full" ON public.daily_staff_sales;
CREATE POLICY "authenticated_full" ON public.daily_staff_sales
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- staff_rates
DROP POLICY IF EXISTS "authenticated_full" ON public.staff_rates;
CREATE POLICY "authenticated_full" ON public.staff_rates
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- monthly_fixed_expenses
DROP POLICY IF EXISTS "authenticated_full" ON public.monthly_fixed_expenses;
CREATE POLICY "authenticated_full" ON public.monthly_fixed_expenses
  FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- ===== 確認用クエリ =====
-- SELECT tablename, rowsecurity FROM pg_tables
-- WHERE schemaname = 'public'
--   AND tablename IN (
--     'company_profile','companies','invoices','accounts_receivable',
--     'daily_sales','daily_staff_sales','staff_rates','monthly_fixed_expenses'
--   );
