-- 日次締め（8時 LINE 通知 + 編集ロック）

-- ===== 締め状態 =====
CREATE TABLE IF NOT EXISTS public.daily_day_closures (
  work_date    DATE PRIMARY KEY,
  closed_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  closed_by    TEXT NOT NULL DEFAULT 'system'
);

CREATE TABLE IF NOT EXISTS public.daily_close_notifications (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  work_date     DATE NOT NULL UNIQUE,
  sent_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  line_status   INTEGER,
  message_body  TEXT NOT NULL,
  error_message TEXT,
  retry_count   INTEGER NOT NULL DEFAULT 0
);

ALTER TABLE public.daily_sales
  ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS closed_by TEXT;

CREATE INDEX IF NOT EXISTS idx_daily_day_closures_closed_at
  ON public.daily_day_closures (closed_at DESC);

CREATE OR REPLACE FUNCTION public.is_work_date_closed(p_work_date DATE)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.daily_day_closures WHERE work_date = p_work_date
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_work_date_closed(DATE) TO anon, authenticated;

-- ===== RLS: daily_sales =====
DROP POLICY IF EXISTS "public_write" ON public.daily_sales;

CREATE POLICY "daily_sales_insert" ON public.daily_sales
  FOR INSERT TO anon
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_sales_insert_auth" ON public.daily_sales
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "daily_sales_update_anon" ON public.daily_sales
  FOR UPDATE TO anon
  USING (NOT public.is_work_date_closed(work_date))
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_sales_update_auth" ON public.daily_sales
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "daily_sales_delete_anon" ON public.daily_sales
  FOR DELETE TO anon
  USING (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_sales_delete_auth" ON public.daily_sales
  FOR DELETE TO authenticated
  USING (true);

-- ===== RLS: daily_staff_sales =====
DROP POLICY IF EXISTS "daily_staff_sales_insert" ON public.daily_staff_sales;
DROP POLICY IF EXISTS "daily_staff_sales_update" ON public.daily_staff_sales;
DROP POLICY IF EXISTS "daily_staff_sales_delete" ON public.daily_staff_sales;

CREATE POLICY "daily_staff_sales_insert_anon" ON public.daily_staff_sales
  FOR INSERT TO anon
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_staff_sales_insert_auth" ON public.daily_staff_sales
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "daily_staff_sales_update_anon" ON public.daily_staff_sales
  FOR UPDATE TO anon
  USING (NOT public.is_work_date_closed(work_date))
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_staff_sales_update_auth" ON public.daily_staff_sales
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "daily_staff_sales_delete_anon" ON public.daily_staff_sales
  FOR DELETE TO anon
  USING (NOT public.is_work_date_closed(work_date));

CREATE POLICY "daily_staff_sales_delete_auth" ON public.daily_staff_sales
  FOR DELETE TO authenticated
  USING (true);

-- ===== RLS: accounts_receivable =====
DROP POLICY IF EXISTS "public_write" ON public.accounts_receivable;

CREATE POLICY "accounts_receivable_insert_anon" ON public.accounts_receivable
  FOR INSERT TO anon
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "accounts_receivable_insert_auth" ON public.accounts_receivable
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "accounts_receivable_update_anon" ON public.accounts_receivable
  FOR UPDATE TO anon
  USING (NOT public.is_work_date_closed(work_date))
  WITH CHECK (NOT public.is_work_date_closed(work_date));

CREATE POLICY "accounts_receivable_update_auth" ON public.accounts_receivable
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "accounts_receivable_delete_anon" ON public.accounts_receivable
  FOR DELETE TO anon
  USING (NOT public.is_work_date_closed(work_date));

CREATE POLICY "accounts_receivable_delete_auth" ON public.accounts_receivable
  FOR DELETE TO authenticated
  USING (true);

-- ===== RLS: shifts (実績時間の匿名更新) =====
DROP POLICY IF EXISTS "public_update" ON public.shifts;

CREATE POLICY "shifts_update_anon" ON public.shifts
  FOR UPDATE TO anon
  USING (date IS NOT NULL AND NOT public.is_work_date_closed(date))
  WITH CHECK (date IS NOT NULL AND NOT public.is_work_date_closed(date));

CREATE POLICY "shifts_update_auth" ON public.shifts
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

-- ===== 締めテーブルは読み取りのみ（書き込みは service_role / Edge Function） =====
ALTER TABLE public.daily_day_closures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_close_notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "daily_day_closures_read" ON public.daily_day_closures
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "daily_close_notifications_read" ON public.daily_close_notifications
  FOR SELECT TO anon, authenticated
  USING (true);

GRANT SELECT ON public.daily_day_closures TO anon, authenticated;
GRANT SELECT ON public.daily_close_notifications TO anon, authenticated;
